services:
  - type: web
    name: neurohire-backend
    runtime: python
    startCommand: "gunicorn backend.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --run-syncdb"
    rootDir: backend
    plan: standard
    envVars:
      - key: SECRET_KEY
        scope: runtime
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "neurohire-backend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://neurohire-bay.vercel.app,https://neurohire.vercel.app"
      - key: MONGODB_URI
        scope: runtime
      - key: GOOGLE_CLIENT_ID
        scope: runtime
      - key: GOOGLE_CLIENT_SECRET
        scope: runtime
